<?php

/**
 * @file
 * Contains embed_image.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function embed_image_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the embed_image module.
    case 'help.page.embed_image':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Embed images based on target_id in Twig templates') . '</p>';
      return $output;

    default:
  }
}
